In [159]:
import pandas as pd;
import numpy as np
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings('ignore')

%matplotlib inline

In [160]:
df = pd.read_csv('Travel.csv')
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

# Data Cleaning

Handling Missing Values
  1. Handling Missing Value
  2. Handling Duplicates
  3. check data type
4. understand the dataset

In [161]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [162]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [163]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [164]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [165]:
df['Gender'] = df['Gender'].replace('Fe Male', 'Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single', 'Unmarried')

In [166]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [167]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [168]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [169]:
## Check Missing Values
## these are the feature with nan value
features_with_na = [features for features in df.columns if df[features].isnull().sum() >= 1]
for feature in features_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5), '% missing values ')

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values

In [170]:
# Statistics on numerical columns (Null cols)
df[features_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [171]:
# Age
df.Age.fillna(df.Age.median(),inplace=True)

#Type of contract 
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)

#Duration of Pitch
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)

#Number of followups
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)

#preferred Property star
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)

#Number of Trips
df.NumberOfTrips.fillna(0,inplace=True)

#Number of children Visiting
df.NumberOfChildrenVisiting.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)

#MonthlyIncome
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

In [172]:

df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [173]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [174]:
df.drop('CustomerID',inplace=True,axis=1)

# Feature Extraction

In [175]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [176]:
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'],axis=1,inplace=True)

In [177]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [178]:
##get all the numeric features

num_features = [feature for feature in  df.columns if df[feature].dtype != 'O']
print('Num of Numerical Feature : ',len(num_features))

Num of Numerical Feature :  12

In [179]:
## Categorical features 
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Feature : ',len(cat_features))

Num of Categorical Feature :  6

In [180]:
## Discrete Feature
discrete_features = [feature for feature in num_features if len(df[feature].unique()) <= 25]
print('Num of Discrete features : ',len(discrete_features))

Num of Discrete features :  9

In [181]:
## continous Feature
continuos_features = [feature for feature in num_features if feature not in discrete_features]
print('Num of Continios feature : ', len(continuos_features))

Num of Continios feature :  3

In [182]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

# Train Test split and model Training

In [183]:
from sklearn.model_selection import train_test_split
X = df.drop(['ProdTaken'],axis = 1)
y = df['ProdTaken']

In [184]:
X.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [185]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [186]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=40)
X_train.shape,X_test.shape

((3910, 17), (978, 17))

In [187]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4888 non-null   float64
 1   TypeofContact           4888 non-null   object
 2   CityTier                4888 non-null   int64
 3   DurationOfPitch         4888 non-null   float64
 4   Occupation              4888 non-null   object
 5   Gender                  4888 non-null   object
 6   NumberOfFollowups       4888 non-null   float64
 7   ProductPitched          4888 non-null   object
 8   PreferredPropertyStar   4888 non-null   float64
 9   MaritalStatus           4888 non-null   object
 10  NumberOfTrips           4888 non-null   float64
 11  Passport                4888 non-null   int64
 12  PitchSatisfactionScore  4888 non-null   int64
 13  OwnCar                  4888 non-null   int64
 14  Designation             4888 non-null   object
 15  MonthlyIncome           4888 non-null   float64
 16  TotalVisiting           4888 non-null   float64
dtypes: float64(7), int64(4), object(6)
memory usage: 649.3+ KB

In [188]:
cat_features = X.select_dtypes(include='object').columns
num_features = X.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [189]:
numeric_transformer = StandardScaler()

In [190]:
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,cat_features),
        ('StandardScaler',numeric_transformer,num_features)
    ]
)

In [191]:
X_train = preprocessor.fit_transform(X_train)

In [192]:
X_test = preprocessor.transform(X_test)

## Random Forest Classifier Training

In [193]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score

In [194]:
models = {
    "Logistic Regression" : LogisticRegression(),
    "Decision Tree" : DecisionTreeClassifier(),
    "Random Forest" : RandomForestClassifier()
}

for i in range(len(list(models))) :
    model = list(models.values())[i]
    model.fit(X_train,y_train) #Train Model

    #Make Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    #Training set performance
    model_train_accuracy = accuracy_score(y_train,y_train_pred)
    model_train_f1 = f1_score(y_train,y_train_pred,average='weighted')
    model_train_precision = precision_score(y_train,y_train_pred)
    model_train_recall = recall_score(y_train,y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)


    # Test set performance
    model_test_accuracy = accuracy_score(y_test,y_test_pred)
    model_test_f1 = f1_score(y_test,y_test_pred,average='weighted')
    model_test_precision = precision_score(y_test,y_test_pred)
    model_test_recall = recall_score(y_test,y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)



    print(list(models.keys())[i])

    print('---------------------------------------')
    print('Model Prediction for Training set')
    print('Accuracy : {:.4f}'.format(model_train_accuracy))
    print('F1 score : {:.4f}'.format(model_train_f1))
    print('Precision : {:.4f}'.format(model_train_precision))
    print('Recall : {:.4f}'.format(model_train_recall))
    print('Roc Auc score : {:.4f}'.format( model_train_rocauc_score))
    

   

    print('---------------------------------------')
    print('Model Prediction for Test set')
    print('Accuracy : {:.4f}'.format(model_test_accuracy))
    print('F1 score : {:.4f}'.format(model_test_f1))
    print('Precision : {:.4f}'.format(model_test_precision))
    print('Recall : {:.4f}'.format(model_test_recall))
    print('Roc Auc score : {:.4f}'.format( model_test_rocauc_score))
    print('---------------------------------------')

Logistic Regression
---------------------------------------
Model Prediction for Training set
Accuracy : 0.8414
F1 score : 0.8142
Precision : 0.6923
Recall : 0.2919
Roc Auc score : 0.6308
---------------------------------------
Model Prediction for Test set
Accuracy : 0.8497
F1 score : 0.8241
Precision : 0.7143
Recall : 0.3056
Roc Auc score : 0.6390
---------------------------------------
Decision Tree
---------------------------------------
Model Prediction for Training set
Accuracy : 1.0000
F1 score : 1.0000
Precision : 1.0000
Recall : 1.0000
Roc Auc score : 1.0000
---------------------------------------
Model Prediction for Test set
Accuracy : 0.8998
F1 score : 0.9008
Precision : 0.7158
Recall : 0.7556
Roc Auc score : 0.8439
---------------------------------------
Random Forest
---------------------------------------
Model Prediction for Training set
Accuracy : 1.0000
F1 score : 1.0000
Precision : 1.0000
Recall : 1.0000
Roc Auc score : 1.0000
---------------------------------------
Model Prediction for Test set
Accuracy : 0.9254
F1 score : 0.9189
Precision : 0.9573
Recall : 0.6222
Roc Auc score : 0.8080
---------------------------------------

#Hyoerparameter Tuning

In [ ]:
rf_params = {
    "max_depth" : [5,8,15,None,10],
    "max_features" : [5,7,"auto",8],
    "min_samples_split" : [2,8,15,20],
    "n_estimators" : [100,200,500,1000]
}

In [196]:
rf_params

{'max_depth': [5, 8, 15, None, 10],
 'max_features': [5, 7, 'auto', 8],
 'min_samples_split': [2, 8, 15, 20],
 'n_estimators': [100, 200, 500, 1000]}

In [197]:
randomcv_models = [
    ("RF",RandomForestClassifier(),rf_params)
]

In [198]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 8, 15, None, 10],
   'max_features': [5, 7, 'auto', 8],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000]})]

In [200]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name,model,params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=params,
                                n_iter = 100,
                                cv=3,
                                verbose=2,
                                n_jobs=1)
    
    random.fit(X_train,y_train)
    model_param[name] = random.best_params_

    for model_name in model_param:
        print(f"---------------Best Params{model_name}---------")
        print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.2s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.8s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.8s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=200; total time=   1.3s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=200; total time=   1.1s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=200; total time=   1.0s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  10.0s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  15.2s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  11.7s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=200; total time=   1.7s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=200; total time=   3.5s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=200; total time=   1.9s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=200; total time=   1.5s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=200; total time=   1.7s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=200; total time=   1.8s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=1000; total time=  13.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=1000; total time=  11.4s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=1000; total time=  10.0s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.9s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.8s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=100; total time=   1.4s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=100; total time=   1.6s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   2.7s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   2.2s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   2.5s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=   7.8s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=   7.6s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=   6.9s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=   6.3s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=   6.2s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=   6.4s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.1s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.9s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.1s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=   2.8s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=   2.9s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=   2.8s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=500; total time=   3.5s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=500; total time=   3.3s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=500; total time=   2.8s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.3s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.1s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.1s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.3s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.4s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.2s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=   7.4s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=   6.9s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=   6.9s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   5.5s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   5.4s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   6.2s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.7s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500; total time=   3.7s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500; total time=   3.4s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500; total time=   3.8s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.8s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=200; total time=   0.8s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.6s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=1000; total time=   5.2s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=1000; total time=   5.2s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=1000; total time=   6.5s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=500; total time=   4.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=500; total time=   3.9s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=500; total time=   4.0s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.5s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.3s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.2s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   4.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.8s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.3s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=  10.1s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=   8.0s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=  10.3s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.5s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.6s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.7s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.3s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.9s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   1.7s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   2.8s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=200; total time=   2.5s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=   3.0s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=   1.4s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=   1.3s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500; total time=   3.4s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500; total time=   4.2s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500; total time=   4.1s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=500; total time=   2.9s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=500; total time=   2.9s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=500; total time=   3.7s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=1000; total time=  11.6s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=1000; total time=   6.3s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=1000; total time=   6.3s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.1s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.7s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.5s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=   9.2s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=   9.1s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=  10.4s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.6s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=200; total time=   0.9s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=   2.7s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=   2.8s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=   2.5s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   3.6s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   7.4s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   3.4s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=1000; total time=   3.5s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=1000; total time=   3.7s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=1000; total time=   3.8s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.0s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.1s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   1.9s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   0.9s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.1s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.6s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.8s

NameError: name 'model_param' is not defined